name: CommediaDell_arte
version: 2.0
main: org.red.CommediaDell_arte
api-version: '1.16'
authors: [Arlecchino, RedKiller]
softdepend:
  - PlaceholderAPI
  - Vault
description: For Fun


commands:
  a_:
    description: "A_ Command"
    permission: op
  banItem:
    description: "Ban Item Command"
    permission: op
  lootChest:
    description: "Loot Chest Command"
    permission: op
  ruleSetting:
    description: "Rule Setting Command"
    permission: op
